### PR TITLE
Hack in branch support

### PR DESCRIPTION
**Pull request by SirOlaf**
Works, but kinda nasty. Would appreciate some feedback

### CODE REVIEW

**Comment by Araq** [comment]
What is the goal?

**Comment by Araq** [comment]
What is the goal?

**Comment by Araq** [comment]
I would much rather see: `requires "x >= #hashX & <= #hashY | >= #hashA & <= #hashB"`. Then we can use tiny packages more effectively that are not tagged.

**Comment by SirOlaf** [comment]
The goal was actually langserver which uses branches, so either its lockfile must be used or branches need to work https://github.com/nim-lang/langserver/blob/master/nimlangserver.nimble#L12

**Comment by elcritch** [comment]
Branches are pretty common during development and team work as well. It's really handy to change `requires "foo"` to `requires "foo#feature-branch"` so others can work with it as well.

**Comment by Araq** [comment]
If desired, needs to be redone again now that we have the new dependency graph. Sorry.

**Pull request closed without merging**
